
/**
 * @description request DOCUMENT details 
 */

export const REQUEST_DOCUMENT_DETAILS = 'REQUEST_DOCUMENT_DETAILS'
export const RECEIVE_DOCUMENT_DETAILS = 'RECEIVE_DOCUMENT_DETAILS'
export const FAILURE_DOCUMENT_DETAILS = 'FAILURE_DOCUMENT_DETAILS'
export const TOGGLE_POPUP = 'TOGGLE_POPUP'
