/**
 * @description request aadhar details 
 */
export const REQUEST_AADHAR_DETAILS = 'REQUEST_AADHAR_DETAILS'
export const RECEIVE_AADHAR_DETAILS = 'RECEIVE_AADHAR_DETAILS'
export const FAILURE_AADHAR_DETAILS = 'FAILURE_AADHAR_DETAILS'

/**
 * @description request DOCUMENT details 
 */

export const REQUEST_DOCUMENT_DETAILS = 'REQUEST_DOCUMENT_DETAILS'
export const RECEIVE_DOCUMENT_DETAILS = 'RECEIVE_DOCUMENT_DETAILS'
export const FAILURE_DOCUMENT_DETAILS = 'FAILURE_DOCUMENT_DETAILS'
export const TOGGLE_POPUP = 'TOGGLE_POPUP'
