export const SAVE_PAN_DETAILS = "SAVE_PAN_DETAILS";
export const SAVE_GEOLOCATION = "SAVE_GEOLOCATION";
export const SAVE_DATE_OF_BIRTH = "SAVE_DATE_OF_BIRTH";
export const SAVE_PINCODE = "SAVE_PINCODE";
export const SAVE_EMPLOYMENT_TYPE = "SAVE_EMPLOYMENT_TYPE";
