
/**
 * @description request activate limit details 
 */
export const REQUEST_ACTIVATE_LIMIT_DETAILS = 'REQUEST_ACTIVATE_LIMIT_DETAILS'
export const RECEIVE_ACTIVATE_LIMIT_DETAILS = 'RECEIVE_ACTIVATE_LIMIT_DETAILS'
export const FAILURE_ACTIVATE_LIMIT_DETAILS = 'FAILURE_ACTIVATE_LIMIT_DETAILS'
export const TOGGLE_POPUP = 'TOGGLE_POPUP'