
/**
 * @description request activate limit details 
 */
export const REQUEST_ACTIVATE_LIMIT_DETAILS = 'REQUEST_ACTIVATE_LIMIT_DETAILS'
export const RECEIVE_ACTIVATE_LIMIT_DETAILS = 'RECEIVE_ACTIVATE_LIMIT_DETAILS'
export const FAILURE_ACTIVATE_LIMIT_DETAILS = 'FAILURE_ACTIVATE_LIMIT_DETAILS'
export const TOGGLE_POPUP = 'TOGGLE_POPUP'
export const FS_LENDING_ACTIVATE_LIMIT_API = 'http://52.183.135.123:8090/tatapay/lending/activate/limit'